version: '3'

services:

  redis:
    restart: always
    image: redis

  rqworker:
    build: backend
    image: dnaweaver/django
    restart: always
    command: ./rqworker_reload.sh
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./backend:/code

  django:
    image: dnaweaver/django
    restart: always
    command: gunicorn website.wsgi:application -b :8082 --reload
    links:
      - redis
      - rqworker
    depends_on:
      - redis
      - rqworker
    volumes:
      - ./backend:/code

  vue:
    restart: always
    image: dnaweaver/vue
    build: frontend
    command: npm run dev
    volumes:
      - ./frontend:/code
      - /code/node_modules

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    links:
      - vue
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx_cuba:/var/log/nginx
